### ISSUE TITLE
对于“本 China IP 库是由 IPIP 和 APNIC 合并而来”的疑议～

### ISSUE THREAD

**Issue by paulgao** [LisonFan/china_ip_list#1]
作为 CHINA_IP_LIST by IPIP 的创建者，对于“本 China IP 库是由 IPIP 和 APNIC 合并而来”是有疑议的。
APNIC 的那个国家数据只能表明申请方的所在国家，但是很多时候不一定是在注册国家使用的。
我们其实已经把标注到 CN 但是不在国内使用，比如用在港澳台甚至跨大洲使用的 IP 段都过滤掉了。
只有标注申请方是CN的，但是未使用的会保留在列表内。

您这么做的结果，只能劣化我们的数据质量。当然如果你发现有数据有问题，欢迎反馈给我们。

恳请考虑我们的疑议。欢迎交流。

**Comment by LisonFan** [comment]
弄这个项目的初衷是方便自己使用，挂在 Github 给我其他的设备同步，没想到这两天突然被关注了。

IP 这块我也不是很懂，我拿 IPIP 和 APNIC 的公开库合并成一个新的 China IP List 的原因主要是我正在使用的一个项目（Pcap_DNSProxy）它的路由模式用的是 APNIC 的库，我就想贵司的公开库和 APNIC 的公开库合并一下应该就挺全的了，虽然会有您说的注册在中国但是不在中国使用的问题。但是我这个项目的初衷是为了方便自己的。。。

**Comment by LisonFan** [comment]
已在 README 中增加了声明

**Comment by paulgao** [comment]
感谢。我是看到有人推荐，所以来说明一下。也建议多试试，你就知道靠 APNIC 的那个数据转换使用，只是一个最简单的方法，但是实际上效果并不好。我们有大量的数据可以表明，尤其是做云主机/VPS的服务商，很多都是 CN 注册的，然后在港澳台甚至全球使用的。当然，碰不上这种例子，比如没被屏蔽的IP不走代理也没事，顶多是慢而已。我们也会用到 APNIC 的数据，但是用途是有限的，比如没有投入使用的才会参照他们的数据做标注。

有机会再聊。

**Comment by paulgao** [comment]
给你一个例子吧。我们公司申请了两段 IP ，103.203.56.0/22 和 116.213.44.0/22，都是 CN 注册，但是在美国广播的。我们库里就不会放入。你可以用我们的 Best Trace 跟踪一下就知道了。比如 103.203.56.1。
